# ===============================
# SERVER 
# ===============================
server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
              
# ===============================
# SPRING 
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost/challenge?useUnicode=true
    username: challenge
    password: javaSpringBoot
  sql:
    init:
      platform: mysql
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none